import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  dts: true,
  outDir: 'dist',
  target: 'es2022',
  platform: 'node',
  external: [
    // Node.js built-in modules
    'fs',
    'path',
    'os',
    'crypto',
    'stream',
    'events',
    'util',
    'url',
    'querystring',
    'http',
    'https',
    'net',
    'tls',
    'zlib',
    'buffer',
    'process',
    'child_process',
    'cluster',
    'worker_threads',
    'perf_hooks',
    'v8',
    'vm',
    'assert',
    'constants',
    'domain',
    'punycode',
    'string_decoder',
    'timers',
    'tty',
    'readline',
    'repl',
    'module',
    'inspector',
    'async_hooks',
    'trace_events',
    // External packages that might have dynamic requires
    'dotenv',
    'pg',
    'postgres',
    'ws',
    'mediasoup',
    'hono',
    'zod',
    'nanoid',
    'iovalkey',
    'resend',
    'rate-limiter-flexible',
    '@hono/node-server',
    '@hono/zod-validator',
    '@t3-oss/env-core',
    'axios',
    'better-auth',
    'drizzle-orm',
    'drizzle-kit',
    '@paralleldrive/cuid2'
  ],
  noExternal: ['@call/auth', '@call/db'],
  clean: true,
  sourcemap: true,
  minify: false,
  splitting: false,
  treeshake: true,
}) 